DROP DATABASE IF EXISTS EMPLOYEE;
CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE EMPLOYEES(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,	
	EMAIL_ID VARCHAR(50),
	PHONE_NUMBER VARCHAR(10),
	SALARY BIGINT,
	GENDER VARCHAR(1));
	
INSERT INTO EMPLOYEES (ID, NAME, EMAIL_ID, PHONE_NUMBER, SALARY, GENDER) VALUES (1,'Jack', 'jack@mail.com', 9999999999, 10000, 'M');
INSERT INTO EMPLOYEES (ID, NAME, EMAIL_ID, PHONE_NUMBER, SALARY, GENDER) VALUES (2,'Mary', 'mary@mail.com', 8888888888, 20000, 'F');
INSERT INTO EMPLOYEES (ID, NAME, EMAIL_ID, PHONE_NUMBER, SALARY, GENDER) VALUES (3,'Sam', 'sam@mail.com', 7777777777, 30000, 'M');
INSERT INTO EMPLOYEES (ID, NAME, EMAIL_ID, PHONE_NUMBER, SALARY, GENDER) VALUES (4,'Harry', 'harry@mail.com', 6666666666, 40000, 'M');
INSERT INTO EMPLOYEES (ID, NAME, EMAIL_ID, PHONE_NUMBER, SALARY, GENDER) VALUES (5,'John', 'john@mail.com', 5555555555, 50000, 'M');